services:
  ros:
    image: racecar_robot:latest
    environment:
      - PYTHONUNBUFFERED=1
      - ROS_DOMAIN_ID=16
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    runtime: nvidia
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/input:/dev/input
    volumes:
      - /dev/shm:/dev/shm
      - ../src/common:/ros2_ws/src/common
      - ../src/robot:/ros2_ws/src/robot
    command: ros2 launch racecar_base bringup.launch
