ekf_node:
  ros__parameters:
    frequency: 50.0

    odom0: /odom
    odom0_config: [ true, true, false, # x, y, z
                    false, false, true, # roll, pitch, yaw
                    true, true, false, # vx, vy, vz
                    false, false, true, # vroll, vpitch, vyaw
                    false, false, false ] # ax, ay, az
    odom0_differential: false
    odom0_queue_size: 1

    # imu0: /imu/data
    # imu0_config: [ false, false, false,
    #                false, false, false,
    #                false, false, false,
    #                false, false, true,
    #                true, true, false ]
    # imu0_differential: false
    # imu0_queue_size: 10

    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    predict_to_current_time: true