# Teleop configuration for PS4 joystick using the x-pad configuration.
bluetooth_teleop:
  teleop_ackermann_joy:
    ros__parameters:
      axis_linear:
        x: 1
      scale_linear:
        x: 1.5
      scale_linear_turbo:
        x: 5.0
      axis_angular:
        yaw: 2
      scale_angular:
        yaw: 0.5
      scale_angular_turbo:
        yaw: 0.2
      enable_button: 4
      enable_turbo_button: 5

  joy_node:
    ros__parameters:
      deadzone: 0.1
      autorepeat_rate: 20.0