networks:
  ros:
services:
  ros:
    image: racecar_simulator:latest
    runtime: nvidia
    environment:
      - ROS_DOMAIN_ID=16
      - LC_NUMERIC=en_US.UTF-8
      # - DISPLAY=novnc:0
      - DISPLAY=:1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONUNBUFFERED=1
    network_mode: host
    # networks:
    #   - ros
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../src/common:/ros2_ws/src/common
      - ../src/common_gpu:/ros2_ws/src/common_gpu
      - ../src/simulator:/ros2_ws/src/simulator
    devices:
      - /dev/input:/dev/input
    command: ros2 launch f1tenth_gym_ros simulator.launch
  # novnc:
  #   build:
  #     context: ./docker-novnc
  #     dockerfile: Dockerfile
  #   environment:
  #     - DISPLAY_WIDTH=1920
  #     - DISPLAY_HEIGHT=1080
  #     - RUN_XTERM=no
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - ros
