networks:
  ros:
services:
  ros:
    build:
      context: ../
      dockerfile: simulator/Dockerfile
    runtime: nvidia
    environment:
      - ROS_DOMAIN_ID=24
      - DISPLAY=novnc:0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONUNBUFFERED=1
    devices:
      - /dev/input:/dev/input
    networks:
      - ros
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../src/common:/ros2_ws/src/common
      - ../src/simulator:/ros2_ws/src/simulator
      - ../maps:/ros2_ws/maps
    # command: ros2 launch racecar_helper empty.launch
    command: ros2 launch racecar_helper map.launch map:=/ros2_ws/maps/berlin/berlin.yaml
  novnc:
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - ros
